# put following info at ~/config/app_config.yml
common:
  s3_bucket_name: reviewumpire_backup
  s3_access_key_id: AKIAJWXU5S7NCXEVW2DQ
  s3_secret_access_key: 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


# put following code as ~/config/initializers/001_app_congfig.rb
require 'ostruct'
require 'yaml'

appconfig       = OpenStruct.new(YAML.load_file("#{Rails.root}/config/app_config.yml"))
env_config      = appconfig.send(Rails.env) rescue nil

appconfig.common.update(env_config) unless env_config.nil?

AppConfig       = OpenStruct.new(appconfig.common)
